'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class SiteMaster

    ''' <summary>
    ''' A1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' A2 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' A3 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' A4 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' MainContent control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
